if(!require(readxl)) install.packages("readxl")
if(!require(dplyr)) install.packages("dplyr")
if(!require(reshape2)) install.packages("reshape2")
if(!require(magrittr)) install.packages("magrittr")
if(!require(rio)) install.packages("rio")
if(!require(janitor)) install.packages("janitor")